### ISSUE TITLE
特定期間のインシデントの一覧の表示

### ISSUE THREAD

**Issue by gr1m0h** [topotal/waroom-roadmap#63]
## Why

現在、期間を絞ってインシデントを表示する際に「未解決」「解決済み」に分かれてしまっている
「未解決」「解決済み」に限らず特定期間のインシデントの一覧を出したい
インシデントを振り返る際に一覧として出力されて、ステータスはラベル的に見えた方がスムーズに振り返りが実施できる

## What

期間を絞ってインシデントを表示する際にステータスによらず一覧を表示する

**Comment by kenta-hi** [comment]
Discussions に記載したので、Issuesの起票はクローズします。

https://github.com/topotal/waroom-roadmap/discussions/64
